site_name: Dnnamo
repo_url: https://github.com/rdadolf/dnnamo
site_description: 'Dnnamo: Tools for Analysis, Modeling, and Optimization of Deep Neural Networks'
google_analytics: ['UA-29492860-4', 'auto']

site_dir: 'deploy'
use_directory_urls: false
theme: 'readthedocs'
extra_css: [assets/dnnamo.css]

pages:
  - 'Getting Started':
    - 'What is Dnnamo?': index.md # Default landing page
    - 'Installation': install.md
    - 'Examples': examples.md # probably want a couple simple, pretty demos here
  - 'Using Dnnamo':
    - 'Analysis': user/analysis.md # maybe separate pages on tools/examples
    - 'Modeling': user/modeling.md # maybe separate pages on tools/examples
    - 'Optimization': user/optimization.md # maybe separate pages on tools/examples
  - 'Developing with Dnnamo':
    - 'Models': dev/models.md
    - 'Loaders': dev/loaders.md
    - 'Frameworks': dev/frameworks.md
    - 'Primops': dev/primops.md

